# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_auto_20171112_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivepost',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
