# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0003_auto_20171113_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivepost',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
